version: "3"
services:
  api:
    build:
     context: ./docker/api
    container_name: api
    env_file:
      - ./project/.env
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ./composer_home/:/var/www/.composer
      - ./project:/var/www/board
  web:
    image: nginx:stable
    command: [nginx-debug, '-g', 'daemon off;']
    container_name: web
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./project:/var/www/board
      - ./docker/web/api.conf:/etc/nginx/conf.d/api.conf:ro

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 127.0.0.1:33066:3306 #for sequel pro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: board
    volumes:
          - /var/www/api/db:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.7
      container_name: phpmyadmin
      links:
       - db
      depends_on:
       - db
      ports:
       - 0.0.0.0:1500:80
      environment:
       - PMA_HOST=db

